## 1
name: Run unit tests

## Actions that will be executed when you push code currently none
on:
  push:

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew build